version: "3.1"

volumes: 
  postgresVolume:

services:
  db:
    image: postgres:9.6.1
    volumes: 
      - postgresVolume:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  hmaraserver:
    build: .
    container_name: hamaraserver1
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/postgres
    volumes: 
      - ./app.js:/src/app/app.js

  hmaraserver2:
    build: .
    container_name: hamaraserver2
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/postgres
    volumes: 
      - ./app.js:/src/app/app.js

  hmaraserver3:
    build: .
    container_name: hamaraserver3
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/postgres
    volumes: 
      - ./app.js:/src/app/app.js
      
  mainserver:
    build: .
    ports:
      - 9000:9000
    volumes: 
      - ./server.js:/src/app/server.js
      - ./serverHandler.js:/src/app/serverHandler.js
    environment: 
      - servers=["http://hamaraserver1:8000", "http://hamaraserver2:8000", "http://hamaraserver3:8000"]
    command: ["nodemon", "/src/app/server.js"]
