version: "3.1"

volumes: 
  postgresVolume:

services:
  db:
    image: postgres:latest
    volumes: 
      - postgresVolume:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  hmaraserver:
    build: .
    container_name: hamaraserver1
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/postgres
    volumes: 
      - .:/src/app/
    links: 
      - db
  hmaraserver2:
    build: .
    container_name: hamaraserver2
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/postgres
    volumes: 
      - .:/src/app/
    links: 
      - db
  hmaraserver3:
    build: .
    container_name: hamaraserver3
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/postgres
    volumes: 
      - .:/src/app/
    links: 
      - db
  mainserver:
    build: .
    ports:
      - 9000:9000
    volumes: 
      - .:/src/app/
    environment: 
      - servers=["http://hamaraserver1:8000", "http://hamaraserver2:8000", "http://hamaraserver3:8000"]
    command: ["nodemon", "/src/app/server.js"]
